sudo: required
dist: bionic
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install ansible
  - pip install flake8
  - pip install wheel       # for ansible-test
  - pip install Jinja2      # for ansible-test
  - pip3 install pyyaml     # for ansible-test
  - pip3 install voluptuous # for ansible-test
  - pip install pyyaml      # for compile test with Python2
  - pip3 install pylint     # for ansible-test
  - pip install yamllint    # for ansible-test
  - pip install pytest      # for pytest
  - pip install pytest-mock # for pytest
  - pip3 install rstcheck
  - pip3 install ansible-doc-extractor
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install lxml
  - pip3 install lxml
  - ansible --version
  
env:
  global:
    secure:  c4sAk/oU6P4d6pyGMeP81RSfV2BrXsXEOVt0BzDJFlPjDw2q2qAlyVLFUXkI9BsSY1+Ql6lKDiIb7l3TNeWAShePzPSrDMmLxfp0NWusccDEy0rDppqrLujlf6eQC/+XZIXgIyIIcUGcMX2qKY6T2oNqqBeuLwdJIy5xKHGgA503EBgHNUgE7JLHLrLiPrjdCl8nCSJYvYvX/CDlhX4eb7bsT/R//bjSkNUgZggNExXDIwsMsin9uZYz9iyKMf6kERluDOzyeH+dCQTGz0iXWEKS0Yk08noPHspg6tfGglNQteFpklLGpxiRqsxscuV1DS9g/JEV0Q83r0glXoo1kD0h65WOWB7U+lgnB/+67fWS8RymdbpNMF5y+tQphXB0fcgRkQmt1Q1pQrlLDfqoAc9/JtcW3KY22vp3cA1FWnxVXtw/9SEk0ipKktgQZC/jc9fpiUekQhPeDVn+gAuTlarnaSvquYFh+2bX+Y7U0ppWrP9kYFGEaT0MCNDE6juMv4/IOKJrBOKU0EHWJELVJqOC/AJaodt7+grEY++j9cZj+9g0VeEwo1oex5b79X2D4cjpBuslt66fEtwRl0wKTcGABEGYCihkkDKo8+f+ueIvyiNwvNPmtjxGXHwQoR50FPgJzI0dM9A7SwWCIVUhnjSNO+5XPRkp0tAfnoH1oZ8=

# command to run tests
script:

  # With flake ignore
  #  E402: <module> level import not at top of file (as per Ansible module developement)
  #  W503: line break before binary operator (PEP8 advices to put logical operator ahead)
  - flake8 plugins/modules/* --max-line-length=160 --ignore=E402,W503
  - flake8 plugins/module_utils/* --max-line-length=160 --ignore=E402,W503
  - flake8 tests/unit/*/* --max-line-length=160 --ignore=E402,W503
  - ansible-galaxy collection build
  - ansible-galaxy collection install ibm-power_hmc*
  - build_path=`pwd`
  - cd /home/travis/.ansible/collections/ansible_collections/ibm/power_hmc

  - pyenv global 3.7 2.7 
  - ansible-test sanity --python 2.7 --skip-test shellcheck
  - ansible-test sanity --python 3.7 --skip-test shellcheck
  - cd /home/travis/.ansible/collections/
  - python -m pytest
  - cd $build_path
  - bash devops/bin/gen_doc.sh

# push the generated documentation using GitHub Pages
deploy:
    provider: pages
    strategy: git
    skip_cleanup: true
    token: $GITHUB_API_KEY
    local_dir: docs/build
    keep_history: true
    on:
        branch: alpha-v1.1.0
