
# install_collections.yml
---
- name: Install Ansible collections on control node
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install collections
      ansible.builtin.shell: |
          uname -a
          cat /etc/*release*
          sudo dnf install sshpass
      register: data

    - debug:
          var: data

