
# install_collections.yml
---
- name: Install Ansible collections on control node
  hosts: localhost
  gather_facts: false
  #become: yes
  tasks:
    - name: Install collections
      ansible.builtin.shell: |
          ls -l ~/.ssh/
          uname -a
          cat /etc/*release*
          ansible-galaxy collection install ibm.power_hmc
      register: data

    - debug:
          var: data

    - name: check the galaxy level
      ansible.builtin.shell: |
          ansible-galaxy collection list
      register: collection_data

    - debug:
          var: collection_data

    - name: Setup lxml
      ansible.builtin.shell: |
          pip install lxml
      register: lxml_status

    - debug:
          var: lxml_status
      

