plugin: ibm.power_hmc.powervm_inventory
hmc_hosts:
  "9.3.84.221":
    user: "hscroot"
    password: "abc123"
compose:
  server_name: SystemName
keyed_groups:
  - prefix: "server_group_"
    key: SystemName
